/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    EditFormArtigo: typeof import('./components/artigos/EditFormArtigo.vue')['default']
    Form: typeof import('./components/artigos/FormArtigo.vue')['default']
    FormArtigo: typeof import('./components/artigos/FormArtigo.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ToolBars: typeof import('./components/navigation/ToolBars.vue')['default']
  }
}
