/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/artigos/': RouteRecordInfo<'/artigos/', '/artigos', Record<never, never>, Record<never, never>>,
    '/artigos/editForm': RouteRecordInfo<'/artigos/editForm', '/artigos/editForm', Record<never, never>, Record<never, never>>,
    '/artigos/form': RouteRecordInfo<'/artigos/form', '/artigos/form', Record<never, never>, Record<never, never>>,
    '/empresa/': RouteRecordInfo<'/empresa/', '/empresa', Record<never, never>, Record<never, never>>,
    '/empresa/editForm': RouteRecordInfo<'/empresa/editForm', '/empresa/editForm', Record<never, never>, Record<never, never>>,
    '/empresa/form': RouteRecordInfo<'/empresa/form', '/empresa/form', Record<never, never>, Record<never, never>>,
    '/eventos/': RouteRecordInfo<'/eventos/', '/eventos', Record<never, never>, Record<never, never>>,
    '/eventos/editForm': RouteRecordInfo<'/eventos/editForm', '/eventos/editForm', Record<never, never>, Record<never, never>>,
    '/eventos/form': RouteRecordInfo<'/eventos/form', '/eventos/form', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/marketplace/': RouteRecordInfo<'/marketplace/', '/marketplace', Record<never, never>, Record<never, never>>,
    '/marketplace/editForm': RouteRecordInfo<'/marketplace/editForm', '/marketplace/editForm', Record<never, never>, Record<never, never>>,
    '/marketplace/form': RouteRecordInfo<'/marketplace/form', '/marketplace/form', Record<never, never>, Record<never, never>>,
  }
}
