/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/artigos/': RouteRecordInfo<'/artigos/', '/artigos', Record<never, never>, Record<never, never>>,
    '/artigos/editForm': RouteRecordInfo<'/artigos/editForm', '/artigos/editForm', Record<never, never>, Record<never, never>>,
    '/artigos/form': RouteRecordInfo<'/artigos/form', '/artigos/form', Record<never, never>, Record<never, never>>,
    '/empresa/': RouteRecordInfo<'/empresa/', '/empresa', Record<never, never>, Record<never, never>>,
    '/empresa/editForm': RouteRecordInfo<'/empresa/editForm', '/empresa/editForm', Record<never, never>, Record<never, never>>,
    '/empresa/form': RouteRecordInfo<'/empresa/form', '/empresa/form', Record<never, never>, Record<never, never>>,
    '/evento/': RouteRecordInfo<'/evento/', '/evento', Record<never, never>, Record<never, never>>,
    '/evento/editForm': RouteRecordInfo<'/evento/editForm', '/evento/editForm', Record<never, never>, Record<never, never>>,
    '/evento/form': RouteRecordInfo<'/evento/form', '/evento/form', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/marketplace/': RouteRecordInfo<'/marketplace/', '/marketplace', Record<never, never>, Record<never, never>>,
    '/marketplace/editForm': RouteRecordInfo<'/marketplace/editForm', '/marketplace/editForm', Record<never, never>, Record<never, never>>,
    '/marketplace/form': RouteRecordInfo<'/marketplace/form', '/marketplace/form', Record<never, never>, Record<never, never>>,
    '/organizacao/': RouteRecordInfo<'/organizacao/', '/organizacao', Record<never, never>, Record<never, never>>,
    '/organizacao/editForm': RouteRecordInfo<'/organizacao/editForm', '/organizacao/editForm', Record<never, never>, Record<never, never>>,
    '/organizacao/form': RouteRecordInfo<'/organizacao/form', '/organizacao/form', Record<never, never>, Record<never, never>>,
    '/users/': RouteRecordInfo<'/users/', '/users', Record<never, never>, Record<never, never>>,
    '/users/editForm': RouteRecordInfo<'/users/editForm', '/users/editForm', Record<never, never>, Record<never, never>>,
    '/users/form': RouteRecordInfo<'/users/form', '/users/form', Record<never, never>, Record<never, never>>,
  }
}
